"""empty message

Revision ID: 113823f49872
Revises: 5d158560062e
Create Date: 2022-12-03 04:30:40.215485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113823f49872'
down_revision = '5d158560062e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sellers_id', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('product_categories_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'sellers', ['sellers_id'], ['id'])
    op.create_foreign_key(None, 'products', 'product_categories', ['product_categories_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'product_categories_id')
    op.drop_column('products', 'sellers_id')
    # ### end Alembic commands ###
