"""empty message

Revision ID: 27291a4fd723
Revises: 113823f49872
Create Date: 2022-12-05 15:06:27.659460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27291a4fd723'
down_revision = '113823f49872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_sellers_id_fkey', 'products', type_='foreignkey')
    op.drop_constraint('products_product_categories_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'product_categories_id')
    op.drop_column('products', 'sellers_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sellers_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('product_categories_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('products_product_categories_id_fkey', 'products', 'product_categories', ['product_categories_id'], ['id'])
    op.create_foreign_key('products_sellers_id_fkey', 'products', 'sellers', ['sellers_id'], ['id'])
    # ### end Alembic commands ###
