"""empty message

Revision ID: 9086f9ca7f59
Revises: 0acc26f1a19a
Create Date: 2023-07-31 09:16:17.128197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9086f9ca7f59'
down_revision = '0acc26f1a19a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'product_subcategories_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'product_subcategories_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
